/// This file can generate README.md by `typlite README.typ`

#let forest = green.darken(20%)
#let is-markdown = sys.inputs.at("x-target", default: "pdf") == "md"
#show regex("github.com|codeberg.org"): text.with(forest)
#show "gistd.myriad-dreamin.com": text.with(eastern)
#show regex("any-gistd.myriad-dreamin.com|@(?:any|http)"): text.with(red)
#show link: text.with(blue)
#show link: underline

#set document(title: "Gistd Documentation") if not is-markdown
#set par(justify: true) if not is-markdown

#let verbatim(body) = {
  show raw.where(lang: "verbatim"): it => html.elem("m1verbatim", attrs: (src: it.text))
  body
}

#if is-markdown {
  verbatim[
    ```verbatim
    <!-- This file is generated by `typlite README.typ` -->
    \[English\] | \[[中文](./docs/README.zh-CN.typ)\]
    # Gistd
    ```
  ]
} else {
  align(center, text(size: 28pt)[Gistd])
}

Instantly share #link("https://typst.app")[typst] documents on git and other network storage.

- #link("https://gistd.myriad-dreamin.com")[Global (Cloudflare CDN)]
- #link("https://gistd-cn.myriad-dreamin.com")[Asia Region (Mirror, 亚洲区域镜像)]

= Loading a document on GitHub

Assuming that you have a GitHub link, for example:

```
https://github.com/typst/templates/blob/main/charged-ieee/template/main.typ
```

Simply replace the `github.com` with `gistd.myriad-dreamin.com`:

```
https://gistd.myriad-dreamin.com/typst/templates/blob/main/charged-ieee/template/main.typ
```

Example Documents:

- https://gistd.myriad-dreamin.com/johanvx/typst-undergradmath/blob/main/undergradmath.typ
- https://gistd.myriad-dreamin.com/Jollywatt/typst-fletcher/blob/main/docs/manual.typ
- https://gistd.myriad-dreamin.com/typst/templates/blob/main/charged-ieee/template/main.typ
- https://gistd.myriad-dreamin.com/Myriad-Dreamin/gistd/blob/main/samples/noto-sans-sc.typ?fonts=google-fonts:Noto+Sans+SC

= View Parameters

These URL parameters can change the behavior of gistd.

- `g-page`: The page number to display. Default is `1`. Only available in the slide mode.
- `g-mode`: The mode to display.
  - `doc`: View the document in the document mode.
  - `slide`: View the document in the slide mode.
- `g-output`: The output format to display.
  - `paged` (default): Render the pages of the document.
  - `html`: Render Typst's HTML export (experimental; requires `g-version` `v0.15.0` or `latest`). The `SVG` / `HTML` switch in the toolbar toggles it.
- `g-version`: The typst compiler version to use.
  - Could be `v0.13.0`, `v0.13.1`, `v0.14.0`, or `latest`.
- `fonts`: Extra font providers to register. This parameter can appear multiple times, and each value must include its provider as `provider:value`.
  - `google-fonts:<family>`: Load the family from Google Fonts, for example `?fonts=google-fonts:Noto+Sans+SC`.
  - Multiple families can be listed by repeating the parameter, for example `?fonts=google-fonts:Noto+Sans+SC&fonts=google-fonts:Roboto`.
  - Google Fonts axis syntax is passed after the family name, for example `?fonts=google-fonts:Roboto:wght@400;700` or `?fonts=google-fonts:Roboto:ital,wght@0,400;1,700`.

= Slide View

Using `g-mode=slide` mentioned above to view the document in the slide mode:

Example Documents:

- #link(
    "https://gistd.myriad-dreamin.com/touying-typ/touying/blob/main/examples/simple.typ?g-mode=slide",
  )[A simple touying side.]

= Loading a document by arbitrary links

Assuming that you have arbitrary link, for example:

```
https://github.com/typst/templates/blob/main/charged-ieee/template/main.typ
```

Put `any-gistd.myriad-dreamin.com` before the link:

```
https://any-gistd.myriad-dreamin.com/github.com/typst/templates/blob/main/charged-ieee/template/main.typ
```

`any-gistd.myriad-dreamin.com` is alias for `gistd.myriad-dreamin.com/@any`.

If a domain (host) is specially identified, gistd will use corresponding approach to serve the document.
- `github.com`: git protocol.
- `codeberg.org`: git protocol.
- `localhost` and others: HTTP protocol if host is `localhost` otherwise https protocol. Note: gistd won't load other files on the specified domain if it cannot identifies the domain, i.e. the typst document cannot load other resources relative to the domain.

Example Documents:

- https://any-gistd.myriad-dreamin.com/github.com/Myriad-Dreamin/gistd/raw/main/README.typ
- https://gistd.myriad-dreamin.com/@any/github.com/Myriad-Dreamin/gistd/raw/main/README.typ

= Loading a document without cors proxy

By default, gistd uses a trusted cors proxy (`https://underleaf.mgt.workers.dev`) to load documents. This is because GitHub and Forgejo doesn't allow gistd to load documents. See #link("https://isomorphic-git.org/docs/en/quickstart")[isomorphic-git: Quickstart] for more details.

However, you may want to load a document without cors proxy. You can do this by adding `g-cors=false` to the query string.

For example, to load a document at `http://localhost:11449/main.typ`:

- https://gistd.myriad-dreamin.com/@http/localhost:11449/main.typ?g-cors=false

= Loading a document with HTTP protocol

`@any` infers protocol from the URL, while you could use `@http` to force HTTP protocol. For example, to load a document at `http://localhost:11449/main.typ`:

- https://gistd.myriad-dreamin.com/@http/localhost:11449/main.typ?g-cors=false


#if is-markdown [
  == Development

  Install dependencies:

  ```
  pnpm install
  ```

  Develop locally:

  ```
  pnpm dev
  ```

  Build:

  ```
  pnpm build
  ```
] else [
  = Using Typst Version

  This document is compiled with typst v#sys.version
]
