/// This file can generate README.md by `typlite README.typ`

#let forest = green.darken(20%)
#let is-markdown = sys.inputs.at("x-target", default: "pdf") == "md"
#show regex("github.com|codeberg.org"): text.with(forest)
#show "gistd-cn.myriad-dreamin.com": text.with(eastern)
#show regex("any-gistd-cn.myriad-dreamin.com|@(?:any|http)"): text.with(red)
#show link: text.with(blue)
#show link: underline

#set document(title: "Gistd 文档") if not is-markdown
#set par(justify: true) if not is-markdown

#let verbatim(body) = {
  show raw.where(lang: "verbatim"): it => html.elem("m1verbatim", attrs: (src: it.text))
  body
}

#if is-markdown {
  verbatim[
    ```verbatim
    <!-- This file is generated by `typlite README.typ` -->
    \[[English](./README.typ)\] | \[中文\]
    # Gistd
    ```
  ]
} else {
  align(center, text(size: 28pt)[Gistd])
}

即时分享托管在在 git 或其他网络服务上的 #link("https://typst.app")[typst] 文档。

- #link("https://gistd.myriad-dreamin.com")[Global (Cloudflare CDN)]
- #link("https://gistd-cn.myriad-dreamin.com")[Asia Region (Mirror, 亚洲区域镜像)]

= 在 GitHub 上加载文档

假设你有一个 GitHub 链接，例如：

```
https://github.com/typst/templates/blob/main/charged-ieee/template/main.typ
```

将 `github.com` 替换为 `gistd-cn.myriad-dreamin.com`:

```
https://gistd-cn.myriad-dreamin.com/typst/templates/blob/main/charged-ieee/template/main.typ
```

示例文档：

- https://gistd-cn.myriad-dreamin.com/johanvx/typst-undergradmath/blob/main/undergradmath.typ
- https://gistd-cn.myriad-dreamin.com/Jollywatt/typst-fletcher/blob/main/docs/manual.typ
- https://gistd-cn.myriad-dreamin.com/typst/templates/blob/main/charged-ieee/template/main.typ
- https://gistd-cn.myriad-dreamin.com/Myriad-Dreamin/gistd/blob/main/samples/noto-sans-sc.typ?fonts=google-fonts:Noto+Sans+SC

== 显示参数

这些 URL 参数可以改变 gistd 的行为。

- `g-page`: 要显示的页面编号。默认是 `1`。仅在幻灯片模式下可用。
- `g-mode`: 显示模式。
  - `doc`: 显示为普通文档。
  - `slide`: 显示为幻灯片。
- `g-output`: 输出格式。
  - `paged`（默认）：按页面渲染文档。
  - `html`: 渲染 Typst 的 HTML 导出（实验性；需要 `g-version` 为 `v0.15.0` 或 `latest`）。也可以通过工具栏的 `SVG` / `HTML` 切换按钮切换。
- `g-refresh`: 每 N 秒检查一次分支（或 URL）是否有更新，有变化时重新编译，例如 `?g-refresh=30`。最小间隔为 10 秒；标签页不可见时暂停检查。
- `g-version`: 所使用的 Typst 编译器版本。
  - 合法值为：`v0.13.0`, `v0.13.1`, `v0.14.0`或`latest`。
- `fonts`: 额外注册的字体 provider。这个参数可以重复出现，每一个值都必须包含 provider，格式是 `provider:value`。
  - `google-fonts:<family>`: 从 Google Fonts 加载字体族，例如 `?fonts=google-fonts:Noto+Sans+SC`。
  - 多个字体族可以通过重复参数指定，例如 `?fonts=google-fonts:Noto+Sans+SC&fonts=google-fonts:Roboto`。
  - Google Fonts 的 axis 语法可以放在 family 后面，例如 `?fonts=google-fonts:Roboto:wght@400;700` 或 `?fonts=google-fonts:Roboto:ital,wght@0,400;1,700`。

== 幻灯片模式

使用上面提到的 `g-mode=slide` 以幻灯片模式显示文档：

示例文档：

- #link(
    "https://gistd-cn.myriad-dreamin.com/touying-typ/touying/blob/main/examples/simple.typ?g-mode=slide",
  )[A simple touying side.]

= 从任意链接加载文档

假设你有一个任意链接，例如：

```
https://github.com/typst/templates/blob/main/charged-ieee/template/main.typ
```

将 `any-gistd-cn.myriad-dreamin.com` 放在链接前面：

```
https://any-gistd-cn.myriad-dreamin.com/github.com/typst/templates/blob/main/charged-ieee/template/main.typ
```

`any-gistd-cn.myriad-dreamin.com` 是 `gistd-cn.myriad-dreamin.com/@any` 的别名。

如果一个域名 (主机) 被特别识别，gistd 将使用相应的方法来服务文档。
- `github.com`: git 协议。
- `codeberg.org`: git 协议。
- `localhost` 和其他: 如果主机是 `localhost` 则使用 HTTP 协议，否则使用 https 协议。注意: gistd 不会加载指定域名上的其他文件，即 typst 文档无法加载相对于域名的其他资源。

示例文档：

- https://any-gistd-cn.myriad-dreamin.com/github.com/Myriad-Dreamin/gistd/raw/main/README.typ
- https://gistd-cn.myriad-dreamin.com/@any/github.com/Myriad-Dreamin/gistd/raw/main/README.typ

= 不使用 cors 代理加载文档

默认情况下，gistd 使用一个受信任的 cors 代理 (`https://underleaf.mgt.workers.dev`) 来加载文档。这是因为 GitHub 和 Forgejo 不允许 gistd 加载文档。请参阅 #link("https://isomorphic-git.org/docs/en/quickstart")[isomorphic-git: Quickstart] 了解更多详情。

然而，你可能想要加载一个没有 cors 代理的文档。你可以通过在查询字符串中添加 `g-cors=false` 来实现。

例如，要加载 `http://localhost:11449/main.typ` 上的文档：

- https://gistd-cn.myriad-dreamin.com/@http/localhost:11449/main.typ?g-cors=false

= 使用 HTTP 协议加载文档

`@any` 从 URL 推断协议，而你可以使用 `@http` 强制使用 HTTP 协议。例如，要加载 `http://localhost:11449/main.typ` 上的文档：

- https://gistd-cn.myriad-dreamin.com/@http/localhost:11449/main.typ?g-cors=false


#if is-markdown [
  == 开发指南

  安装依赖：

  ```
  pnpm install
  ```

  本地开发：

  ```
  pnpm dev
  ```

  构建：

  ```
  pnpm build
  ```
] else [
  = Typst版本

  这个文档由 typst v#sys.version 编译。
]
